---
artifact: ${project.groupId}:${project.artifactId}:${project.version}
name: "OpenShift"
metadata:
  keywords:
  - "kubernetes"
  - "openshift"
  guide: "https://quarkus.io/guides/openshift"
  categories:
  - "cloud"
  status: "stable"