---
artifact: ${project.groupId}:${project.artifactId}:${project.version}
name: "OpenShift"
metadata:
  keywords:
  - "kubernetes"
  - "openshift"
  guide: "https://quarkus.io/guides/deploying-to-openshift"
  categories:
  - "cloud"
  status: "stable"
  config:
  - "quarkus.container-image."
  - "quarkus.kubernetes."
  - "quarkus.openshift."
