version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "23:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 3
    labels:
      - area/dependencies
    allow:
      - dependency-name: org.jboss:jboss-parent
      - dependency-name: org.apache.activemq:artemis-core-client
      - dependency-name: org.apache.activemq:artemis-jms-client
      - dependency-name: org.apache.activemq:artemis-server
      - dependency-name: org.apache.activemq:artemis-commons
      - dependency-name: org.flywaydb:flyway-core
      - dependency-name: org.liquibase:liquibase-core
      - dependency-name: org.freemarker:freemarker
      - dependency-name: org.eclipse.jgit:org.eclipse.jgit
      - dependency-name: org.eclipse.jgit:org.eclipse.jgit.http.server
      - dependency-name: io.fabric8:kubernetes-client-bom
      - dependency-name: org.apache.httpcomponents:httpclient
      - dependency-name: org.apache.httpcomponents:httpasyncclient
      - dependency-name: org.apache.httpcomponents:httpcore
      - dependency-name: org.quartz-scheduler:quartz
      - dependency-name: com.cronutils:cron-utils
      - dependency-name: org.eclipse:yasson
      - dependency-name: org.yaml:snakeyaml
      - dependency-name: com.google.guava:guava
      # Quarkus
      - dependency-name: io.quarkus.gizmo:gizmo
      - dependency-name: io.quarkus.http:quarkus-http-vertx-backend
      - dependency-name: io.quarkus.http:quarkus-http-core
      - dependency-name: io.quarkus.http:quarkus-http-servlet
      - dependency-name: io.quarkus.http:quarkus-http-websockets-jsr
      # Elytron
      - dependency-name: org.wildfly.security:wildfly-elytron
      - dependency-name: org.wildfly.security:wildfly-elytron-*
      # JDBC Drivers
      - dependency-name: org.postgresql:postgresql
      - dependency-name: org.mariadb.jdbc:mariadb-java-client
      - dependency-name: mysql:mysql-connector-java
      - dependency-name: org.apache.derby:derbyclient
      # Kafka
      - dependency-name: org.apache.kafka:kafka-clients
      - dependency-name: org.apache.kafka:kafka-streams
      - dependency-name: org.apache.kafka:kafka_2.12
      - dependency-name: org.apache.zookeeper:zookeeper
      # Debezium
      - dependency-name: io.debezium:debezium-core
      # Scala
      - dependency-name: org.scala-lang:scala-reflect
      - dependency-name: org.scala-lang:scala-library
      - dependency-name: org.scala-lang:scala-compiler
      - dependency-name: net.alchim31.maven:scala-maven-plugin
      # SmallRye
      - dependency-name: io.smallrye:smallrye-jwt
      - dependency-name: io.smallrye:smallrye-health
      - dependency-name: io.smallrye:smallrye-metrics
      - dependency-name: io.smallrye:smallrye-open-api
      - dependency-name: io.smallrye:smallrye-opentracing
      - dependency-name: io.smallrye:smallrye-fault-tolerance
      - dependency-name: io.smallrye:smallrye-context-propagation
      - dependency-name: io.smallrye.common:smallrye-common-bom
      - dependency-name: io.smallrye.config:smallrye-config
      - dependency-name: io.smallrye.reactive:mutiny
      - dependency-name: io.smallrye.reactive:smallrye-reactive-messaging
      # Swagger-UI
      - dependency-name: org.webjars:swagger-ui
      # Tika
      - dependency-name: org.apache.tika:tika-parsers
      # RX Java 2
      - dependency-name: io.reactivex.rxjava2:rxjava
      # Test dependencies
      - dependency-name: io.rest-assured:*
      - dependency-name: org.junit:junit-bom
      - dependency-name: org.assertj:assertj-core
      - dependency-name: org.testcontainers:testcontainers-bom
      - dependency-name: org.testcontainers:testcontainers
      - dependency-name: org.testcontainers:postgresql
      - dependency-name: org.mockito:mockito-core
      - dependency-name: org.mockito:mockito-junit-jupiter
      - dependency-name: org.awaitility:awaitility
      # Maven plugins
      - dependency-name: net.revelc.code.formatter:formatter-maven-plugin
      - dependency-name: net.revelc.code:impsort-maven-plugin
      # Narayana
      - dependency-name: org.jboss.narayana.jta:narayana-jta
      - dependency-name: org.jboss.narayana.jts:narayana-jts-integration
      - dependency-name: org.jboss.narayana.stm:stm
      # Agroal
      - dependency-name: io.agroal:agroal-api
      - dependency-name: io.agroal:agroal-pool
      - dependency-name: io.agroal:agroal-narayana
      #Jandex
      - dependency-name: org.jboss:jandex
      - dependency-name: org.jboss.jandex:jandex-maven-plugin
      #Neo4j
      - dependency-name: org.neo4j.driver:neo4j-java-driver
      #WireMock
      - dependency-name: com.github.tomakehurst:wiremock-jre8
      - dependency-name: uk.co.automatictester:wiremock-maven-plugin
      #Picocli
      - dependency-name: info.picocli:picocli
      - dependency-name: info.picocli:picocli-codegen
      # Caffeine
      - dependency-name: com.github.ben-manes.caffeine:caffeine
      # Jackson
      - dependency-name: com.fasterxml.jackson:jackson-bom
      # AWS
      - dependency-name: software.amazon.awssdk:bom
      - dependency-name: software.amazon.awssdk:apache-client
      - dependency-name: com.amazon.alexa:ask-sdk
      - dependency-name: com.amazon.alexa:ask-sdk-apache-client
      - dependency-name: com.amazonaws:aws-lambda-java-events
      # Apache Commons
      - dependency-name: commons-io:commons-io
      # Micrometer
      - dependency-name: io.micrometer:micrometer-bom
      - dependency-name: io.micrometer:micrometer-registry-stackdriver
      # BouncyCastle
      - dependency-name: org.bouncycastle:bcprov-jdk15on
      - dependency-name: org.bouncycastle:bctls-jdk15on
      - dependency-name: org.bouncycastle:bc-fips
    rebase-strategy: disabled
  - package-ecosystem: gradle
    directory: "/integration-tests/gradle"
    schedule:
      interval: daily
      time: "21:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 3
    labels:
      - area/dependencies
    rebase-strategy: disabled
  - package-ecosystem: gradle
    directory: "/devtools/gradle"
    schedule:
      interval: daily
      time: "21:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 3
    labels:
      - area/dependencies
    rebase-strategy: disabled
