---
artifact: ${project.groupId}:${project.artifactId}:${project.version}
name: "Kubernetes"
metadata:
  keywords:
  - "kubernetes"
  guide: "https://quarkus.io/guides/kubernetes"
  categories:
  - "cloud"
  status: "stable"
  config:
  - "quarkus.container-image."
  - "quarkus.kubernetes."
  - "quarkus.openshift."
  - "quarkus.knative."
