---
artifact: ${project.groupId}:${project.artifactId}:${project.version}
name: "Minikube"
metadata:
  keywords:
  - "kubernetes"
  - "minikube"
  guide: "https://quarkus.io/guides/kubernetes"
  categories:
  - "cloud"
  status: "stable"