# Documentation in https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "security"
      - match:
          dependency_name: "org.flywaydb:flyway-core"
      - match:
          dependency_name: "org.eclipse.jgit:org.eclipse.jgit"
      - match:
          dependency_name: "io.fabric8:kubernetes-client-bom"
      # JDBC Drivers
      - match:
          dependency_name: "org.postgresql:postgresql"
      - match:
          dependency_name: "org.mariadb.jdbc:mariadb-java-client"
      - match:
          dependency_name: "mysql:mysql-connector-java"
      - match:
          dependency_name: "org.apache.derby:derbyclient"
      - match:
          dependency_name: "com.microsoft.sqlserver:mssql-jdbc"
