# Documentation in https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "area/dependencies"
    allowed_updates:
      - match:
          update_type: "security"
      - match:
          dependency_name: "org.apache.activemq:artemis-core-client"
      - match:
          dependency_name: "org.apache.activemq:artemis-jms-client"
      - match:
          dependency_name: "org.apache.activemq:artemis-server"
      - match:
          dependency_name: "org.apache.activemq:artemis-commons"
      - match:
          dependency_name: "org.flywaydb:flyway-core"
      - match:
          dependency_name: "org.liquibase:liquibase-core"
      - match:
          dependency_name: "org.freemarker:freemarker"
      - match:
          dependency_name: "org.eclipse.jgit:org.eclipse.jgit"
      - match:
          dependency_name: "org.eclipse.jgit:org.eclipse.jgit.http.server"
      - match:
          dependency_name: "io.fabric8:kubernetes-client-bom"
      - match:
          dependency_name: "org.apache.httpcomponents:httpclient"
      - match:
          dependency_name: "org.apache.httpcomponents:httpasyncclient"
      - match:
          dependency_name: "org.apache.httpcomponents:httpcore"
      - match:
          dependency_name: "org.quartz-scheduler:quartz"
      - match:
          dependency_name: "com.cronutils:cron-utils"
      - match:
          dependency_name: "org.eclipse:yasson"
      - match:
          dependency_name: "org.yaml:snakeyaml"
      # Quarkus
      - match:
          dependency_name: "io.quarkus.gizmo:gizmo"
      - match:
          dependency_name: "io.quarkus.http:quarkus-http-vertx-backend"
      - match:
          dependency_name: "io.quarkus.http:quarkus-http-core"
      - match:
          dependency_name: "io.quarkus.http:quarkus-http-servlet"
      - match:
          dependency_name: "io.quarkus.http:quarkus-http-websockets-jsr"
      # Elytron
      - match:
          dependency_name: "org.wildfly.security:wildfly-elytron-*"
      # JDBC Drivers
      - match:
          dependency_name: "org.postgresql:postgresql"
      - match:
          dependency_name: "org.mariadb.jdbc:mariadb-java-client"
      - match:
          dependency_name: "mysql:mysql-connector-java"
      - match:
          dependency_name: "org.apache.derby:derbyclient"
      # Kafka
      - match:
          dependency_name: "org.apache.kafka:kafka-clients"
      - match:
          dependency_name: "org.apache.kafka:kafka-streams"
      - match:
          dependency_name: "org.apache.kafka:kafka_2.12"
      - match:
          dependency_name: "org.apache.zookeeper:zookeeper"
      # Debezium
      - match:
          dependency_name: "io.debezium:debezium-core"
      # Scala
      - match:
          dependency_name: "org.scala-lang:scala-reflect"
      - match:
          dependency_name: "org.scala-lang:scala-library"
      - match:
          dependency_name: "org.scala-lang:scala-compiler"
      - match:
          dependency_name: "net.alchim31.maven:scala-maven-plugin"
      # Smallrye
      - match:
          dependency_name: "io.smallrye:smallrye-jwt"
      - match:
          dependency_name: "io.smallrye:smallrye-health"
      - match:
          dependency_name: "io.smallrye:smallrye-metrics"
      - match:
          dependency_name: "io.smallrye:smallrye-open-api"
      - match:
          dependency_name: "io.smallrye:smallrye-opentracing"
      - match:
          dependency_name: "io.smallrye:smallrye-fault-tolerance"
      - match:
          dependency_name: "io.smallrye:smallrye-context-propagation"
      - match:
          dependency_name: "io.smallrye.config:smallrye-config"
      - match:
          dependency_name: "io.smallrye.reactive:mutiny"
      - match:
          dependency_name: "io.smallrye.reactive:smallrye-reactive-messaging"
      - match:
          dependency_name: "io.smallrye.reactive:smallrye-reactive-streams-operators"
      # Tika
      - match:
          dependency_name: "org.apache.tika:tika-parsers"
      # RX Java 2
      - match:
          dependency_name: "io.reactivex.rxjava2:rxjava"
      # Test dependencies
      - match:
          dependency_name: "io.rest-assured:rest-assured"
      - match:
          dependency_name: "io.rest-assured:json-schema-validator"
      - match:
          dependency_name: "org.junit:junit-bom"
      - match:
          dependency_name: "org.assertj:assertj-core"
      - match:
          dependency_name: "org.testcontainers:testcontainers"
      - match:
          dependency_name: "org.testcontainers:postgresql"
      - match:
          dependency_name: "org.mockito:mockito-core"
      - match:
          dependency_name: "org.awaitility:awaitility"
      # Maven plugins
      - match:
          dependency_name: "net.revelc.code.formatter:formatter-maven-plugin"
      - match:
          dependency_name: "net.revelc.code:impsort-maven-plugin"
      # Narayana
      - match:
          dependency_name: "org.jboss.narayana.jta:narayana-jta"
      - match:
          dependency_name: "org.jboss.narayana.jts:narayana-jts-integration"
      - match:
          dependency_name: "org.jboss.narayana.stm:stm"
      # Agroal
      - match:
          dependency_name: "io.agroal:agroal-api"
      - match:
          dependency_name: "io.agroal:agroal-pool"
      - match:
          dependency_name: "io.agroal:agroal-narayana"
      #Jandex
      - match:
          dependency_name: "org.jboss:jandex"
      - match:
          dependency_name: "org.jboss.jandex:jandex-maven-plugin"
      #Neo4j
      - match:
          dependency_name: "org.neo4j.driver:neo4j-java-driver"
      #WireMock
      - match:
          dependency_name: "com.github.tomakehurst:wiremock-jre8"
      - match:
          dependency_name: "uk.co.automatictester:wiremock-maven-plugin"
  - package_manager: "java:gradle"
    directory: "/devtools/gradle"
    update_schedule: "daily"
    default_labels:
      - "area/dependencies"

  # 1.3
  - package_manager: "java:maven"
    target_branch: 1.3
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "area/dependencies"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "java:gradle"
    target_branch: 1.3
    directory: "/devtools/gradle"
    update_schedule: "daily"
    default_labels:
      - "area/dependencies"
    allowed_updates:
      - match:
          update_type: "security"
