on:
    issues:
        type: [opened]

jobs:
    autolabel:
      runs-on: ubuntu-latest
      name: auto label
      steps:
      - name: issuelabeler
        uses: docker://maxandersen/jbang-issuelabeler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
          CONFIG: https://raw.githubusercontent.com/quarkusio/quarkus/master/.github/autoissuelabeler.yml
          
