name: Jakarta Rewrite

on:
  workflow_dispatch:
  schedule:
    # 4am every weekday + saturday
    - cron: '0 4 * * 1-6'
jobs:
  rewrite:
    runs-on: ubuntu-latest
    name: Rewrite to Jakarta
    if: github.repository == 'quarkusio/quarkus'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Install JBang
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
        shell: bash
      - name: Transform sources
        run: |
          export PATH="$HOME/.jbang/bin:$PATH"
          git checkout -b temp-jakarta-rewrite
          REWRITE_TESTS_CONTAINERS=true ./jakarta/transform.sh
          git add .
          git commit -m 'Transform sources to Jakarta'
        shell: bash
      - name: Push changes to jakarta-rewrite
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.JAKARTA_PUSH_PAT }}
          force: true
          branch: jakarta-rewrite
      - name: Report status
        if: "always() && github.repository == 'quarkusio/quarkus'"
        shell: bash
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - app setup
          ~/.jbang/bin/jbang .github/NativeBuildReport.java \
            issueNumber=24396 \
            runId=${{ github.run_id }} \
            status=${{ job.status }} \
            token=${{ secrets.GITHUB_API_TOKEN }} \
            issueRepo=${{ github.repository }} \
            thisRepo=${{ github.repository }}
