name: Quarkus Release Test Build

on:
  schedule:
    - cron: '0 3 * * 2'
env:
  LANG: en_US.UTF-8
jobs:
  build:
    name: "Prepare release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh
      - name: Set up JDK 8
        # Uses sha for added security since tags can be updated
        uses: joschi/setup-jdk@68381f2c0646f942f70b69f8e81fe10e1ed5d293
        with:
          java-version: 8
      - name: Create maven repo
        run: mkdir -p $HOME/release/repository
      - name: Build and Test
        run: |
          mvn --settings .github/mvn-settings.xml \
            -DskipITs -Dinvoker.skip=true \
            -Dmaven.repo.local=$HOME/release/repository \
            clean install
